# Generated by Django 4.2.1 on 2024-10-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePermiso', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombreRol',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', to='crud.permiso'),
        ),
    ]
