# Generated by Django 4.2.1 on 2024-10-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_permiso_alter_rol_nombrerol_remove_rol_permisos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.usuario')),
                ('nombreUsuario', models.CharField(max_length=32)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.rol')),
            ],
            bases=('crud.usuario',),
        ),
    ]
