# Generated by Django 4.2.1 on 2024-10-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_usuarioempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=100)),
                ('descripcionCategoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.usuario')),
                ('nombre_chatbot', models.CharField(max_length=32)),
                ('activo', models.BooleanField(default=True)),
            ],
            bases=('crud.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.usuario')),
                ('direccion', models.CharField(max_length=255)),
            ],
            bases=('crud.usuario',),
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo_pago', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaOrden', models.DateTimeField(auto_now_add=True)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.usuario')),
                ('nombre_contacto_proveedor', models.CharField(max_length=32)),
            ],
            bases=('crud.usuario',),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('ordencompra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.ordencompra')),
                ('estado_carrito', models.BooleanField(default=True)),
            ],
            bases=('crud.ordencompra',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ordencompra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.ordencompra')),
                ('estadoPedido', models.BooleanField(default=True)),
                ('estadoPago', models.BooleanField(default=True)),
            ],
            bases=('crud.ordencompra',),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReporte', models.CharField(max_length=100)),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadMinima', models.IntegerField()),
                ('cantidadActual', models.IntegerField()),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.categoria')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario'),
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.chatbot')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.cliente')),
            ],
        ),
    ]
