# Generated by Django 5.1.2 on 2024-10-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_remove_ordencompra_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Telefónico'),
        ),
    ]
