# Generated by Django 5.1.2 on 2024-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_usuario_numero_telefonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen de categoría'),
        ),
    ]
