# Generated by Django 5.1.2 on 2024-11-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_remove_categoria_imagen_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen_path',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_path',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/categorias'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/productos'),
        ),
    ]
